/**
 * auto-title
 *
 * Automatically gives every session a short topic title so the session
 * selector (/resume) shows meaningful names instead of raw first messages.
 *
 * How it works:
 * - New sessions: after the first exchange settles (agent_settled), the
 *   conversation is summarized into a short title and applied with
 *   pi.setSessionName().
 * - Old sessions that still have no name (e.g. created before this
 *   extension was installed) get a title on session start / resume / fork.
 * - Existing names are never overwritten, so a name set via /name always
 *   wins. Only sessions without a name are auto-titled.
 *
 * Titles are always in English (ASCII), generated by a cheap model:
 * deepseek/deepseek-v4-flash first, openai-codex/gpt-5.6-luna second,
 * falling back to the active model.
 *
 * Commands:
 *   /autotitle          force (re)generate the title now
 *   /autotitle show     show the current session name
 *   /autotitle on|off   enable/disable auto-titling for this session
 *
 * Environment:
 *   PI_AUTOTITLE=0      disable auto-titling entirely
 *   PI_AUTOTITLE_MODEL  override the title model, e.g.
 *                       "deepseek/deepseek-v4-flash"
 */

import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import {
	buildConversationSample as buildSampleFromMessages,
	cleanTitle,
	type ConversationMessage,
	DEFAULT_TITLE_MODELS,
	extractText,
	formatSessionTimestamp,
	TITLE_TIMEOUT_MS,
	withTimeout,
} from "./helpers.ts";

const STATE_ENTRY_TYPE = "auto-title-state";

type TitleState = { disabled?: boolean };

const getConversationSample = (ctx: ExtensionContext): string => {
	const messages: ConversationMessage[] = [];

	for (const entry of ctx.sessionManager.getBranch()) {
		if (entry.type !== "message") {
			continue;
		}

		const role = entry.message.role;
		if (role !== "user" && role !== "assistant") {
			continue;
		}

		const text = extractText(entry.message.content).trim();
		if (text) {
			messages.push({ role, text });
		}
	}

	return buildSampleFromMessages(messages);
};

export default function (pi: ExtensionAPI) {
	// Guards: one naming pass at a time, and never touch a session after
	// this extension instance has been shut down (session switch / quit).
	let naming = false;
	let shuttingDown = false;

	pi.on("session_shutdown", () => {
		shuttingDown = true;
	});

	const isGloballyEnabled = () => process.env.PI_AUTOTITLE !== "0";

	const isDisabledForSession = (ctx: ExtensionContext): boolean => {
		let state: TitleState | undefined;
		for (const entry of ctx.sessionManager.getEntries()) {
			if (entry.type === "custom" && entry.customType === STATE_ENTRY_TYPE) {
				state = entry.data as TitleState | undefined;
			}
		}
		return state?.disabled === true;
	};

	const pickModels = (ctx: ExtensionContext) => {
		const specs = process.env.PI_AUTOTITLE_MODEL
			? [process.env.PI_AUTOTITLE_MODEL]
			: DEFAULT_TITLE_MODELS;
		const models: NonNullable<typeof ctx.model>[] = [];

		const addModel = (candidate: typeof ctx.model) => {
			if (
				candidate &&
				ctx.modelRegistry.hasConfiguredAuth(candidate) &&
				!models.some((model) => model?.provider === candidate.provider && model.id === candidate.id)
			) {
				models.push(candidate);
			}
		};

		for (const spec of specs) {
			const slash = spec.indexOf("/");
			if (slash <= 0 || slash >= spec.length - 1) {
				continue;
			}
			addModel(ctx.modelRegistry.find(spec.slice(0, slash), spec.slice(slash + 1)));
		}

		addModel(ctx.model);

		for (const candidate of ctx.modelRegistry.getAvailable()) {
			if (ctx.modelRegistry.hasConfiguredAuth(candidate)) {
				addModel(candidate);
				break;
			}
		}

		return models;
	};

	const completeTitleRequest = async (
		ctx: ExtensionContext,
		model: NonNullable<typeof ctx.model>,
		messages: Array<{
			role: "user";
			content: Array<{ type: "text"; text: string }>;
			timestamp: number;
		}>,
	) => {
		const controller = new AbortController();
		const parentSignal = ctx.signal;
		const abortFromParent = () => controller.abort();

		if (parentSignal) {
			if (parentSignal.aborted) {
				controller.abort();
			} else {
				parentSignal.addEventListener("abort", abortFromParent, { once: true });
			}
		}

		const requestOptions = {
			// Codex currently ignores maxTokens, but keep it for adapters that honor
			// the shared option. Its backend rejects max_output_tokens, so do not
			// inject that OpenAI Responses field here.
			maxTokens: model.reasoning ? 1000 : 80,
			...(model.api === "openai-codex-responses"
				? { reasoningEffort: "low" as const }
				: {}),
			...(model.reasoning ? {} : { temperature: 0 }),
			timeoutMs: TITLE_TIMEOUT_MS,
			cacheRetention: "none" as const,
			signal: controller.signal,
		};

		try {
			const request = ctx.modelRegistry.complete(model, { messages }, requestOptions);
			return await withTimeout(
				request,
				TITLE_TIMEOUT_MS,
				`title request timed out after ${TITLE_TIMEOUT_MS / 1000}s`,
				() => controller.abort(),
			);
		} finally {
			parentSignal?.removeEventListener("abort", abortFromParent);
			controller.abort();
		}
	};

	const generateTitle = async (
		ctx: ExtensionContext,
		sample: string,
		cwdLabel: string | undefined,
	): Promise<string | undefined> => {
		const models = pickModels(ctx);
		if (models.length === 0) {
			throw new Error("no configured model is available for auto-title");
		}

		const lines = [
			"You are naming a chat session. Write a short title that captures the topic and goal of the conversation below.",
			"",
			"Rules:",
			"- Output ONLY the title text, nothing else. No explanations, no quotes, no trailing period.",
			"- At most 40 characters.",
			"- Use sentence case, not title case.",
			"- ALWAYS write the title in English using ASCII characters only, even if the conversation is in another language.",
			"- No emoji, no markdown formatting.",
		];
		if (cwdLabel) {
			lines.push(`- The session runs in the project "${cwdLabel}"; mention it only when it helps.`);
		}
		lines.push("", "<conversation>", sample, "</conversation>");

		const messages = [
			{
				role: "user" as const,
				content: [{ type: "text" as const, text: lines.join("\n") }],
				timestamp: Date.now(),
			},
		];
		const failures: string[] = [];

		for (const model of models) {
			try {
				if (ctx.hasUI) {
					ctx.ui.notify(`Generating title with ${model.provider}/${model.id}...`, "info");
				}
				const response = await completeTitleRequest(ctx, model, messages);
				if (response.stopReason === "error") {
					throw new Error(response.errorMessage || "model returned an error");
				}
				if (response.stopReason === "aborted") {
					throw new Error("title request was aborted");
				}

				const title = response.content
					.filter((c): c is { type: "text"; text: string } => c.type === "text")
					.map((c) => c.text)
					.join(" ")
					.trim();
				const cleaned = cleanTitle(title);
				if (cleaned) {
					return cleaned;
				}
				throw new Error("model returned an empty title");
			} catch (err) {
				const message = err instanceof Error ? err.message : String(err);
				failures.push(`${model.provider}/${model.id}: ${message}`);
				console.warn(`[auto-title] ${model.provider}/${model.id} failed; trying fallback`, message);
			}
		}

		throw new Error(failures.join("; "));
	};

	const maybeAutoTitle = async (ctx: ExtensionContext, force = false): Promise<void> => {
		if (naming || shuttingDown || !isGloballyEnabled()) {
			return;
		}
		if (!force && pi.getSessionName()) {
			return;
		}
		if (!force && isDisabledForSession(ctx)) {
			return;
		}

		let sample: string;
		let cwdLabel: string | undefined;
		let sessionTimestamp: string;
		try {
			if (!ctx.sessionManager.getSessionFile()) {
				return; // ephemeral session, nothing to name
			}
			sessionTimestamp = ctx.sessionManager.getHeader()?.timestamp ?? "";
			if (!sessionTimestamp || !formatSessionTimestamp(sessionTimestamp)) {
				return; // persisted sessions should always have a valid header timestamp
			}
			sample = getConversationSample(ctx);
			if (!sample) {
				return; // no conversation yet
			}
			const base = ctx.cwd.split("/").filter(Boolean).pop();
			cwdLabel = base ? base : undefined;
		} catch {
			return; // stale context (session switched mid-flight) or teardown
		}

		naming = true;
		try {
			const title = await generateTitle(ctx, sample, cwdLabel);
			if (!title || shuttingDown) {
				return;
			}
			if (!pi.getSessionName() || force) {
				const timestamp = formatSessionTimestamp(sessionTimestamp);
				if (!timestamp) {
					return;
				}
				const titledSessionName = `${title} (${timestamp})`;
				pi.setSessionName(titledSessionName);
				if (ctx.hasUI) {
					ctx.ui.notify(`Session titled: ${titledSessionName}`, "info");
				}
			}
		} catch (err) {
			if (!shuttingDown) {
				const message = err instanceof Error ? err.message : String(err);
				console.error("[auto-title] failed to generate title:", err);
				if (ctx.hasUI) {
					ctx.ui.notify(`Auto-title failed: ${message}`, "warning");
				}
			}
		} finally {
			naming = false;
		}
	};

	// Main path for new sessions: name it once the first exchange settles.
	pi.on("agent_settled", (_event, ctx) => {
		void maybeAutoTitle(ctx);
	});

	// Old sessions with content but no name yet (resume / startup / fork).
	pi.on("session_start", (event, ctx) => {
		if (event.reason === "reload") {
			return;
		}
		void maybeAutoTitle(ctx);
	});

	pi.registerCommand("autotitle", {
		description:
			"Auto-title: regenerate session title (/autotitle), show it (/autotitle show), or toggle for this session (/autotitle on|off)",
		handler: async (args, ctx) => {
			const arg = args.trim().toLowerCase();

			if (arg === "show") {
				const name = pi.getSessionName();
				const disabled = isDisabledForSession(ctx);
				ctx.ui.notify(name ? `Session: ${name}` : "No session name", "info");
				if (ctx.hasUI) {
					ctx.ui.notify(disabled ? "Auto-title: off" : "Auto-title: on", "info");
				}
				return;
			}

			if (arg === "on" || arg === "off") {
				pi.appendEntry(STATE_ENTRY_TYPE, { disabled: arg === "off" });
				ctx.ui.notify(
					`Auto-title ${arg === "on" ? "enabled" : "disabled"} for this session`,
					"info",
				);
				if (arg === "on") {
					void maybeAutoTitle(ctx);
				}
				return;
			}

			if (arg === "") {
				ctx.ui.notify("Generating title...", "info");
				await maybeAutoTitle(ctx, true);
				return;
			}

			ctx.ui.notify("Usage: /autotitle [show|on|off]", "warning");
		},
	});
}
